{
  "name": "Customer Profitability Sample PBIX_V1",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Fact",
        "isHidden": true,
        "lineageTag": "393366fb-afe3-4214-8542-e9249cd14f0b",
        "columns": [
          {
            "name": "Customer Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "lineageTag": "868cdb8f-6ed7-41be-b403-86021fb6f245",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "lineageTag": "05724996-ec43-4b5f-a4f3-514c29e47ebb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "BU Key",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BU Key",
            "lineageTag": "aca9363a-9fe0-4fc4-b6ac-8693599e9e2f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Scenario Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Scenario Key",
            "lineageTag": "0b18b873-9ffa-439c-a510-609a392a1b36",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Revenue",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Revenue",
            "lineageTag": "d35d8612-6c64-4ee7-8d89-fcfcdbe2b2df",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Material Costs",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Material Costs",
            "lineageTag": "d5ea7ef3-5451-4ca8-bd67-89c2ad5386ed",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Labor Costs Variable",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Labor Costs Variable",
            "lineageTag": "c9e1e443-e6c7-4633-9846-f26e88f59c2c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Taxes",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Taxes",
            "lineageTag": "6f4bd135-fa80-415f-811d-e3fcdcf727b3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Rev for Exp Travel",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rev for Exp Travel",
            "lineageTag": "5ec2aba4-17a4-4ac5-a5fb-c7f610364fa0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Travel Expenses",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Travel Expenses",
            "lineageTag": "d417ce2c-13bc-4579-9d36-09f3a22679d4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Cost Third Party",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Cost Third Party",
            "lineageTag": "ff50ab89-6e34-4486-9c0d-4963ca9ae212",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Subscription Revenue",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Subscription Revenue",
            "lineageTag": "ca673206-de89-4010-b317-f213dc9deebc",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "YearPeriod",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "YearPeriod",
            "lineageTag": "4c8c1cff-4ced-4f86-825d-167b3a93457b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 YearPeriod#(lf)      ,[KNDNR] [Customer Key]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,1 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.20 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f, mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 210 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'#(lf)union all #(lf)SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 PeriodYear#(lf)      ,[KNDNR] [Customer]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,2 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.4 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f tablesample (85 percent),  mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 300 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Customer Key\", \"Customer Key\"}, {\"Product Key\", \"Product Key\"}, {\"BU Key\", \"BU Key\"}, {\"Scenario Key\", \"Scenario Key\"}, {\"Revenue\", \"Revenue\"}, {\"Material Costs\", \"Material Costs\"}, {\"Labor Costs Variable\", \"Labor Costs Variable\"}, {\"Taxes\", \"Taxes\"}, {\"Rev for Exp Travel\", \"Rev for Exp Travel\"}, {\"Travel Expenses\", \"Travel Expenses\"}, {\"Cost Third Party\", \"Cost Third Party\"}, {\"Subscription Revenue\", \"Subscription Revenue\"}, {\"YearPeriod\", \"YearPeriod\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Customer Key\", Int64.Type}, {\"Product Key\", type text}, {\"BU Key\", type number}, {\"Scenario Key\", Int64.Type}, {\"Revenue\", type number}, {\"Material Costs\", type number}, {\"Labor Costs Variable\", type number}, {\"Taxes\", type number}, {\"Rev for Exp Travel\", type number}, {\"Travel Expenses\", type number}, {\"Cost Third Party\", type number}, {\"Subscription Revenue\", type number}, {\"YearPeriod\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Revenue",
            "expression": "SUM([Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "0d2f90ee-49af-4e89-b1af-611b5c4f2885",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Material Costs",
            "expression": "SUM([Material Costs])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "068203c0-5588-4196-9c40-b8cad45fe856",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Labor Costs Variable",
            "expression": "SUM([Labor Costs Variable])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "929bf375-3b6a-4e7b-b927-4c99e8b83278",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Taxes",
            "expression": "SUM([Taxes])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "de085e84-9938-4ef9-b908-a4b549bc0b52",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Rev for Exp Travel",
            "expression": "SUM([Rev for Exp Travel])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ad827ee1-afe2-4705-8e07-b1efcc0fa934",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Travel Expenses",
            "expression": "SUM([Travel Expenses])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1d7bd0a5-f657-49c5-8c7b-fbc4220cda06",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Cost Third Party",
            "expression": "SUM([Cost Third Party])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4a542212-762a-4125-b375-f111aa298734",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Subscription Revenue",
            "expression": "SUM([Subscription Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "eeea4f7e-fad9-480f-8efd-0c26cd7fa5c7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Gross Margin",
            "expression": "[Total Revenue]-[Total COGS]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4679cfb3-e35d-4008-948c-30af7dc2cbf1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "GM%",
            "expression": "DIVIDE([Gross Margin],[Total Revenue])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "fb05de02-7368-491d-b59e-29e9a5244de2"
          },
          {
            "name": "YTD Revenue",
            "expression": "TOTALYTD(SUM([Revenue]),'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "0069c196-f62d-4dc5-bf8b-f5d94b78e8e1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Total COGS",
            "expression": "[Sum of Material Costs]+[Sum of Labor Costs Variable]+[Sum of Taxes]+[Sum of Rev for Exp Travel]+[Sum of Travel Expenses]+[Sum of Cost Third Party]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a3619eec-6df9-45bc-9c29-27770e901de2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD COGS",
            "expression": "TOTALYTD([Total COGS],'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a4ba2c0b-d4c0-4ea0-a976-148875a3c061",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD Gross Margin",
            "expression": "TOTALYTD([Gross Margin],'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "fc44474a-57e9-4a2f-bfa1-f1820addef44",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Revenue SPLY",
            "expression": "CALCULATE([Total Revenue],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e249201f-c4b3-48a1-a0f1-d6e476f6e60b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Gross Margin SPLY",
            "expression": "CALCULATE([Gross Margin],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1d978af1-0df3-4d15-89a0-c753c34a681d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "GM% SPLY",
            "expression": "[Gross Margin SPLY]/[Revenue SPLY]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "21f59609-11fe-4cc9-9ebf-e87ba3ce9f2b"
          },
          {
            "name": "YTD GM%",
            "expression": "[YTD Gross Margin]/[YTD Revenue]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "055fa1ef-4932-49b1-965d-88232c40ead8"
          },
          {
            "name": "YTD Revenue SPLY",
            "expression": "CALCULATE([YTD Revenue],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "f7d0f6ea-c50f-4f09-a2b1-b8873a8e9d28",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "COGS SPLY",
            "expression": "CALCULATE([Total COGS],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "9e15e54f-8d09-4bf8-a029-d42c369cdec8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD COGS SPLY",
            "expression": "CALCULATE([YTD COGS],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "01d50086-0c2d-4aa4-820d-d23e5de3c592",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD GM% SPLY",
            "expression": "[YTD GM SPLY]/[YTD Revenue SPLY]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5ed58e6c-15c5-4bbc-b298-d68ac98aa20b"
          },
          {
            "name": "YTD GM SPLY",
            "expression": "CALCULATE([YTD Gross Margin],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "14aa6100-235e-4b0f-84e8-58fb63158862",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY Rev Var",
            "expression": "[Total Revenue]-[Revenue SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "0eb32daa-2293-4bf9-af53-a9c0e31c28be",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY GM Var",
            "expression": "[Gross Margin]-[Gross Margin SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a4139f06-adc1-43f9-a64e-e56f501e6b04",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY Rev Growth",
            "expression": "IF([Revenue SPLY],[YoY Rev Var]/[Revenue SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "bb45ccf8-9a6c-41aa-aad0-b4efd5ea8e14"
          },
          {
            "name": "YoY GM Growth",
            "expression": "IF([Gross Margin SPLY],[YoY GM Var]/[Gross Margin SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "9c20c7b9-63e7-4caf-85c7-e4cbc6c91f0b"
          },
          {
            "name": "YoY YTD Rev Var",
            "expression": "[YTD Revenue]-[YTD Revenue SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8d385346-1f65-4592-aa2c-146966d55007",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY COGS Var",
            "expression": "[Total COGS]-[COGS SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "125194ea-08e0-4bec-8c07-5c7965d3ba5c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY YTD COGS Var",
            "expression": "[YTD COGS]-[YTD COGS SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d39f34c8-ca7d-48b2-8048-1b84a80927ea",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY YTD GM% Var",
            "expression": "[YTD GM%]-[YTD GM% SPLY]",
            "formatString": "#,0",
            "lineageTag": "d81d9c1a-c123-432c-a502-6cb27be3bf67"
          },
          {
            "name": "YoY YTD GM Var",
            "expression": "[YTD Gross Margin]-[YTD GM SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "3d7b9f4c-3ed3-45f5-93fa-bbdec74831b9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY GM %Var",
            "expression": "[GM%]-[GM% SPLY]",
            "lineageTag": "90cb8560-e3d9-4c25-afc3-641fdd8993b7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "YoY YTD Rev Growth",
            "expression": "IF([YTD Revenue SPLY],[YoY YTD Rev Var]/[YTD Revenue SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "608835f3-7523-4450-be1b-7dc4bee3cc9f"
          },
          {
            "name": "YoY COGS Growth",
            "expression": "IF([COGS SPLY],[YoY COGS Var]/[COGS SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "70b036c3-3e61-4835-b819-08e9c07b122f"
          },
          {
            "name": "YoY YTD COGS Growth",
            "expression": "IF([YTD COGS SPLY],[YoY YTD COGS Var]/[YTD COGS SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a5dfa3ca-2ac1-45a0-a847-392fe5d8c697"
          },
          {
            "name": "YoY YTD GM Growth",
            "expression": "IF([YTD GM SPLY],[YoY YTD GM Var]/[YTD GM SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7c916582-37e0-4ee0-818b-e6ba73ccc9d3"
          },
          {
            "name": "# of Customers",
            "expression": "DISTINCTCOUNT([Customer Key])",
            "lineageTag": "2ee77072-fbb0-415e-94fe-9e94e13b6be4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "# of Products",
            "expression": "DISTINCTCOUNT([Product Key])",
            "lineageTag": "be70403d-d51a-4f1b-a805-92a731c0b403"
          },
          {
            "name": "Revenue Budget",
            "expression": "CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]=\"Budget\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "37984f6f-681b-47d0-b839-6afcba7f9fa1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Revenue Var to Budget",
            "expression": "[RevenueTY]-[Revenue Budget]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a77ba0c1-466a-48ec-a30d-3c1fbe4f0124",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Revenue Var % to Budget",
            "expression": "DIVIDE([Revenue Var to Budget], [RevenueTY])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2dbceb2b-4130-4c8f-ad51-25f6487034be"
          },
          {
            "name": "RevenueTY",
            "expression": "CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]=\"Actual\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a667b800-7cbe-443b-b015-aec17eec2ccc",
            "kpi": {
              "targetExpression": "'Fact'[Revenue Budget]",
              "targetFormatString": "\\$#,0;(\\$#,0);\\$#,0",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='Fact'[RevenueTY]/'Fact'[_RevenueTY Goal] return",
                "if(ISBLANK(x),BLANK(),",
                "        If(x<0.95,-1,",
                "\t    If(x<1,0,1)",
                "    )",
                ")",
                ""
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "Measure"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Percentage"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "95"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "100"
                }
              ]
            },
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Revenue",
            "expression": "SUM('Fact'[Revenue])",
            "lineageTag": "c76d4d27-84d4-40ad-9da6-716268b34dce",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ]
      },
      {
        "name": "BU",
        "lineageTag": "9729eebf-ae32-4aba-977a-4f8fbc8d53d2",
        "columns": [
          {
            "name": "BU Key",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BU Key",
            "lineageTag": "b2a12e07-1784-4718-8dfc-3e20f41aa86d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "BU",
            "dataType": "string",
            "sourceColumn": "BU",
            "lineageTag": "ce642276-7220-42cf-92db-b5594a000934",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Division",
            "dataType": "string",
            "sourceColumn": "Division",
            "lineageTag": "66b6ad14-5f53-4785-96b4-c53166a12880",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Executive_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Executive_id",
            "lineageTag": "a9c1de42-e53f-4546-b4fc-354c140ee120",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "BU",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT #(lf)       #(lf)      [Profit Center Key] [BU Key],#(lf)   BU,#(lf)   Division, Executive_id#(lf)  FROM [MDS].[mdm].[profitcenter]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"BU Key\", \"BU Key\"}, {\"BU\", \"BU\"}, {\"Division\", \"Division\"}, {\"Executive_id\", \"Executive_id\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"BU Key\", type number}, {\"BU\", type text}, {\"Division\", type text}, {\"Executive_id\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "BUHierarchy",
            "lineageTag": "fe054a7d-f397-406a-afe6-7cc2d38e832b",
            "levels": [
              {
                "name": "Division",
                "ordinal": 0,
                "column": "Division",
                "lineageTag": "ab51b23d-a817-4697-94d8-e21de72666e8"
              },
              {
                "name": "BU",
                "ordinal": 1,
                "column": "BU",
                "lineageTag": "17854e38-1188-4358-92be-8a5c7041e42d"
              }
            ]
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "2917d3b2-270c-4534-bb4c-81fd411c79e6",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "YearPeriod",
            "dataType": "string",
            "sourceColumn": "YearPeriod",
            "lineageTag": "aa8d9ce4-2aff-4ceb-806c-e8e49a388267",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "lineageTag": "0cb9f006-2948-4a81-acfb-40ce7461e257",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Period",
            "dataType": "string",
            "sourceColumn": "Period",
            "lineageTag": "3d05c600-ce86-4993-902f-cd83ce61a17e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "General Date",
            "lineageTag": "7fef2999-e8a5-4b10-88ac-cfc1d5e1e2f9",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "db9c55a6-9978-4ac0-88b4-4f07ed8945a3",
                "defaultHierarchy": {
                  "table": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "sortByColumn": "Period",
            "lineageTag": "c5d29265-761f-4bed-a484-bf2710426360",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "QtrID",
            "dataType": "string",
            "sourceColumn": "QtrID",
            "lineageTag": "1abbdbbc-0904-4c57-9da1-94e0681934a5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Qtr",
            "dataType": "string",
            "sourceColumn": "Qtr",
            "lineageTag": "61e8783a-ab1f-4efa-9f78-6bf4603226d8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT#(lf)       concat([Year], [period]) YearPeriod#(lf)#(tab)  ,[Year]#(lf)      ,[Period]#(lf)      ,[Date]#(lf)      ,[Month]#(lf)      ,[QtrID]#(lf)      ,[Qtr]#(lf)  FROM [MDS].[mdm].[fiscalperiod]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"YearPeriod\", \"YearPeriod\"}, {\"Year\", \"Year\"}, {\"Period\", \"Period\"}, {\"Date\", \"Date\"}, {\"Month\", \"Month\"}, {\"QtrID\", \"QtrID\"}, {\"Qtr\", \"Qtr\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"YearPeriod\", type text}, {\"Year\", Int64.Type}, {\"Period\", type text}, {\"Date\", type datetime}, {\"Month\", type text}, {\"QtrID\", type text}, {\"Qtr\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "YQM",
            "lineageTag": "fc5a4d99-ab68-4e8c-a453-d6a3185c81d5",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "fe2b8092-394a-4213-8c42-69b111724b8e"
              },
              {
                "name": "Qtr",
                "ordinal": 1,
                "column": "Qtr",
                "lineageTag": "1d543a7b-6c64-4443-94aa-4277ae3b0dcc"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "404e1018-05fc-45d9-a85d-7c76601d4e1b"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LegacyCustomDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Scenario",
        "lineageTag": "3ce8e8a7-0304-496a-896b-7eb86894dbda",
        "columns": [
          {
            "name": "Scenario Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Scenario Key",
            "lineageTag": "0828ac81-3833-4061-a23e-c1104a302cb2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Scenario",
            "dataType": "string",
            "sourceColumn": "Scenario",
            "lineageTag": "9f1bac8f-2867-47af-ad88-5fd174b7824a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Scenario",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUXJMLilNzFGK1YlWMgJynUpT0lNLlGJjAQ==\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Column1\", \"Scenario Key\"}, {\"Column2\", \"Scenario\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Scenario Key\", Int64.Type}, {\"Scenario\", type text}})",
                " in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Product",
        "lineageTag": "a3f345a3-b17e-46b4-a66f-712ed84ba8d7",
        "columns": [
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "lineageTag": "45e0ec61-c65d-4210-b430-ef2ad46a3a88",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product",
            "lineageTag": "ea39a8ba-7b97-41cb-a81d-bca23e3e8f0e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMjRQ0lEKzi9LVIrViVYyAvECijJzS4vBfGMQ3yW/KD8dIm8C4rvnJKZkQhVYgAR8PXXNjSBcI5B8aV5eapFSbCwA\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Column1\", \"Product Key\"}, {\"Column2\", \"Product\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Product Key\", Int64.Type}, {\"Product\", type text}})",
                " in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Customer",
        "lineageTag": "c28867dd-733b-4f59-bf7f-89ed254ed414",
        "columns": [
          {
            "name": "Customer",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Customer",
            "lineageTag": "a8834140-a18f-4ee0-a9a0-273644fc8ead",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Country/Region",
            "dataType": "string",
            "sourceColumn": "Country/Region",
            "lineageTag": "2d33db26-208e-4f32-8c60-7f2195060fff",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "6dd4439d-8f1c-42fa-8fe8-cd1c6088fa72",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "9869b942-e569-45a3-898e-c5692d461f29",
            "dataCategory": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Postal Code",
            "dataType": "double",
            "sourceColumn": "Postal Code",
            "lineageTag": "088ccd6d-e438-4052-9207-f73b35263e5c",
            "dataCategory": "PostalCode",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "35bf6abb-a7c2-49e9-9054-b490f5233be3",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Industry ID",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Industry ID",
            "lineageTag": "bb5e1e0c-6275-46fd-85c2-6c615f5743f7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\mad\\Dropbox\\Work\\Obvience\\IP\\Customer and Product Profitability\\Data\\dimCustomer.xlsx\"), null, true),",
                "    Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Promoted Headers\", {{\"Customer\", \"Customer\"}, {\"Country\", \"Country/Region\"}, {\"Name\", \"Name\"}, {\"City\", \"City\"}, {\"Postal Code\", \"Postal Code\"}, {\"State\", \"State\"}, {\"Industry ID\", \"Industry ID\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Customer\", type number}, {\"Country/Region\", type text}, {\"Name\", type text}, {\"City\", type text}, {\"Postal Code\", type number}, {\"State\", type text}, {\"Industry ID\", type number}})",
                " in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "CustomerHierarchy",
            "lineageTag": "908ea65f-7cc3-4a40-8fbf-9fe002a63a0c",
            "levels": [
              {
                "name": "Country",
                "ordinal": 0,
                "column": "Country/Region",
                "lineageTag": "f0a63500-c13b-4276-be5d-01e3d72632dc"
              },
              {
                "name": "State",
                "ordinal": 1,
                "column": "State",
                "lineageTag": "09366ba1-81dd-42be-b27e-953df3b957a7"
              },
              {
                "name": "City",
                "ordinal": 2,
                "column": "City",
                "lineageTag": "875a1b14-8e88-42e6-af33-8b025ffda13e"
              },
              {
                "name": "Postal Code",
                "ordinal": 3,
                "column": "Postal Code",
                "lineageTag": "630c1ec6-6766-4a8a-a05c-8c010c8b1353"
              },
              {
                "name": "Customer",
                "ordinal": 4,
                "column": "Customer",
                "lineageTag": "190a08a4-bc19-48ae-ac46-e31617b10e73"
              }
            ]
          }
        ]
      },
      {
        "name": "Industry",
        "lineageTag": "ee425bed-3438-4ea0-8ddc-11e53e9d0d56",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "ID",
            "keepUniqueRows": true,
            "lineageTag": "1fcc1cf9-c708-477d-9250-72231b7401d0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Industry",
            "dataType": "string",
            "sourceColumn": "Industry",
            "keepUniqueRows": true,
            "lineageTag": "20322504-ca51-4e98-905b-f327d308e8f1",
            "isDefaultLabel": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Image",
            "dataType": "binary",
            "sourceColumn": "Image",
            "lineageTag": "d1bb9541-7a8c-4d06-a399-8115b037ec21",
            "dataCategory": "Image",
            "isDefaultImage": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Industry",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT [dbo].[Industry].*   FROM [dbo].[Industry]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ID\", \"ID\"}, {\"Industry\", \"Industry\"}, {\"Image\", \"Image\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ID\", Int64.Type}, {\"Industry\", type text}, {\"Image\", type binary}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Executive",
        "lineageTag": "04c2e3c4-8b71-4cc8-b83e-2b3455db9d55",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "ID",
            "keepUniqueRows": true,
            "lineageTag": "aeab814b-84e7-4639-8310-13d5bc4415f0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "f8b855ba-2f06-4b72-abc1-12713bea7392",
            "isDefaultLabel": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Img",
            "dataType": "binary",
            "sourceColumn": "Img",
            "lineageTag": "31d5016c-44f8-4865-bfca-5f3779ebdb11",
            "dataCategory": "Image",
            "isDefaultImage": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Executive",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT [dbo].[Executive].*   FROM [dbo].[Executive]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ID\", \"ID\"}, {\"Name\", \"Name\"}, {\"Img\", \"Img\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ID\", Int64.Type}, {\"Name\", type text}, {\"Img\", type binary}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "State",
        "lineageTag": "51bb8b33-2cc6-42f5-af69-30de1722ee2a",
        "columns": [
          {
            "name": "StateCode",
            "dataType": "string",
            "sourceColumn": "StateCode",
            "lineageTag": "a9eee23d-65c5-4cc4-9a57-698492f8fae9",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "a8ea40ca-2a70-4e00-8e7f-db4542915222",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "942a1522-93db-4c19-977b-44aa3745c8c8",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "State",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"select StateShort StateCode, StateName State, Region from MDS.mdm.state\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"StateCode\", \"StateCode\"}, {\"State\", \"State\"}, {\"Region\", \"Region\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"StateCode\", type text}, {\"State\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_fe310476-3bb5-422b-85ff-9fd23f2cad67",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "ea6b55b4-4ce3-4670-a8c2-122910205fdf",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "164cdb7b-1bf7-4373-82cb-32e1cfc586a3",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "39bfe48b-6b4f-4729-b9f1-dd1c37b7057f",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "b9e2c5f5-e68f-488d-be41-5cb12527e946",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "7e3d118d-7d2e-4b2b-886c-628925035474",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "52b3e7bc-1a7f-4a58-9672-e34f34bd7032",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "eaf3ef02-3b97-484f-8caf-faa33aee4cf4",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "74a6bd26-c588-4521-9c32-bc121a56a60a",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_fe310476-3bb5-422b-85ff-9fd23f2cad67-d67cdec0-80dc-4d14-91dc-f2af07fffba5",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "021a4a9a-4b27-43f6-adc1-b8de0f7d5236",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "6e07ff92-e40e-4779-b74d-9154fc64091a"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "647633aa-59f1-4d2f-ab1d-176d00a5ced3"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "5897dab2-86f8-458a-87af-b5d4f859f369"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "e703c9f0-9ee6-443a-95c7-109bc4d7472b"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "21e15472-4087-416a-9b62-780b63c56e83",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "7fadb1c3-1f1c-4ddd-9667-a20810491dd1",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "9f456cbf-90f4-4be7-8763-83b90e77fffe",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "d440a9c0-cf3b-4359-9935-9dc4a8a7843d",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "1473d48b-5308-41c1-833f-0b9ce6dda417",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "807f13ac-cd27-4f8b-a2a6-60d299bde81d",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "bca6fb7f-3ad7-446c-af5e-7ce5a1552241",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "fd286bae-b079-48de-afab-db735ed8475c",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4-a8d78949-1742-4a86-af0b-cf59b84d8989",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Date'[Date])), 1, 1), Date(Year(MAX('Date'[Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "3b4bc806-88db-4a56-af0d-688526bbd3c8",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "58a58789-a63b-4714-acbb-12985c603d70"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "a4d614ae-752d-4835-bc88-cfdfa2336274"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "19394bf0-1dc7-4f73-80e8-452385b2cc85"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "a2d88bda-f9b6-4aca-b46c-a062d42aa3df"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "e8085e9d-6dc8-4c8e-a37d-a25c76158541",
        "fromTable": "Fact",
        "fromColumn": "BU Key",
        "toTable": "BU",
        "toColumn": "BU Key"
      },
      {
        "name": "e2d69975-1445-43f8-9008-c580d8b85e9d",
        "fromTable": "Fact",
        "fromColumn": "YearPeriod",
        "toTable": "Date",
        "toColumn": "YearPeriod"
      },
      {
        "name": "ae136884-d40d-4899-942c-0668a79c7420",
        "fromTable": "Fact",
        "fromColumn": "Scenario Key",
        "toTable": "Scenario",
        "toColumn": "Scenario Key"
      },
      {
        "name": "996dfaa0-cf16-4f01-9fee-9f472b727b09",
        "fromTable": "Fact",
        "fromColumn": "Product Key",
        "toTable": "Product",
        "toColumn": "Product Key"
      },
      {
        "name": "ec7a5ef0-70cf-4abe-8ac4-364a5e22f7c7",
        "fromTable": "Fact",
        "fromColumn": "Customer Key",
        "toTable": "Customer",
        "toColumn": "Customer"
      },
      {
        "name": "6d6ab90a-1617-476a-9783-aecb116ac11d",
        "fromTable": "BU",
        "fromColumn": "Executive_id",
        "toTable": "Executive",
        "toColumn": "ID"
      },
      {
        "name": "9249475f-a768-45d9-845e-83b653ccc793",
        "fromTable": "Customer",
        "fromColumn": "Industry ID",
        "toTable": "Industry",
        "toColumn": "ID"
      },
      {
        "name": "f433c520-c9a7-4ee0-a489-f737798ca886",
        "fromTable": "Customer",
        "fromColumn": "State",
        "toTable": "State",
        "toColumn": "StateCode"
      },
      {
        "name": "db9c55a6-9978-4ac0-88b4-4f07ed8945a3",
        "fromTable": "Date",
        "fromColumn": "Date",
        "toTable": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US",
            "DynamicImprovement": "HighConfidence"
          },
          "contentType": "json"
        }
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.110.1085.0 (22.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Fact\",\"BU\",\"Date\",\"Scenario\",\"Product\",\"Customer\",\"Industry\",\"Executive\",\"State\"]"
      }
    ]
  }
}