{
  "name": "Customer Profitability Sample PBIX_V1",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Fact",
        "isHidden": true,
        "lineageTag": "d786abf8-89b9-40d9-b821-2df9c39d1939",
        "columns": [
          {
            "name": "Customer Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "lineageTag": "079d4788-3d2b-4647-ac50-3cdb3d5e1c00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "lineageTag": "041ba962-e52b-48a7-a81b-b794a555848b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "BU Key",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BU Key",
            "lineageTag": "f64215c8-a288-424d-88e6-d7c19f4b894d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Scenario Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Scenario Key",
            "lineageTag": "84aaf47e-8557-4a89-a86d-db475b67f9c4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Revenue",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Revenue",
            "lineageTag": "e0b63beb-3e6b-4510-89f5-48f1f201f67c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Material Costs",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Material Costs",
            "lineageTag": "79aa8da2-9d62-49b1-a6b1-a82daa46bc65",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Labor Costs Variable",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Labor Costs Variable",
            "lineageTag": "c76b3c68-2a52-4b5b-b1f7-7e8b49f544ac",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Taxes",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Taxes",
            "lineageTag": "65aa1746-ccc7-43ba-96ec-72e2ced3b810",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Rev for Exp Travel",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rev for Exp Travel",
            "lineageTag": "f24696ac-aa71-4ed1-8261-674470f1662d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Travel Expenses",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Travel Expenses",
            "lineageTag": "456ba34a-0a18-4cec-b935-0ac39f7198bf",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Cost Third Party",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Cost Third Party",
            "lineageTag": "94366a6b-58b1-44e5-a139-dbe98baa65bd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Subscription Revenue",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Subscription Revenue",
            "lineageTag": "cf6b9128-71e6-46f4-a4b9-a466f30aae74",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "YearPeriod",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "YearPeriod",
            "lineageTag": "0c6c4838-f118-4ff8-a21d-ee8c09347811",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 YearPeriod#(lf)      ,[KNDNR] [Customer Key]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,1 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.20 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f, mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 210 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'#(lf)union all #(lf)SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 PeriodYear#(lf)      ,[KNDNR] [Customer]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,2 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.4 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f tablesample (85 percent),  mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 300 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Customer Key\", \"Customer Key\"}, {\"Product Key\", \"Product Key\"}, {\"BU Key\", \"BU Key\"}, {\"Scenario Key\", \"Scenario Key\"}, {\"Revenue\", \"Revenue\"}, {\"Material Costs\", \"Material Costs\"}, {\"Labor Costs Variable\", \"Labor Costs Variable\"}, {\"Taxes\", \"Taxes\"}, {\"Rev for Exp Travel\", \"Rev for Exp Travel\"}, {\"Travel Expenses\", \"Travel Expenses\"}, {\"Cost Third Party\", \"Cost Third Party\"}, {\"Subscription Revenue\", \"Subscription Revenue\"}, {\"YearPeriod\", \"YearPeriod\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Customer Key\", Int64.Type}, {\"Product Key\", type text}, {\"BU Key\", type number}, {\"Scenario Key\", Int64.Type}, {\"Revenue\", type number}, {\"Material Costs\", type number}, {\"Labor Costs Variable\", type number}, {\"Taxes\", type number}, {\"Rev for Exp Travel\", type number}, {\"Travel Expenses\", type number}, {\"Cost Third Party\", type number}, {\"Subscription Revenue\", type number}, {\"YearPeriod\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Revenue",
            "expression": "SUM([Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "83e938bf-d0cc-4317-b611-814f3853541e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Material Costs",
            "expression": "SUM([Material Costs])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "075a40b6-68ce-4417-a428-9f1ba771d7c2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Labor Costs Variable",
            "expression": "SUM([Labor Costs Variable])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "fd1c4838-ffaa-4576-8f21-05f1eb9d98f3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Taxes",
            "expression": "SUM([Taxes])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "3701fad6-ee01-4968-8822-f81b66998279",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Rev for Exp Travel",
            "expression": "SUM([Rev for Exp Travel])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6945ebe0-10d3-4693-8e91-11d303f60d5d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Travel Expenses",
            "expression": "SUM([Travel Expenses])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6e96ce74-5843-44bf-a820-771d4da2b874",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Cost Third Party",
            "expression": "SUM([Cost Third Party])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4861c3e3-e29e-4cf6-9e9c-81c5fdd0b589",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Subscription Revenue",
            "expression": "SUM([Subscription Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "bfe381ca-6f09-4d52-b614-3c0724fafb96",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Gross Margin",
            "expression": "[Total Revenue]-[Total COGS]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e51f9bfb-c3b1-4596-b1e8-90692f368d4d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "GM%",
            "expression": "DIVIDE([Gross Margin],[Total Revenue])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "bfa81f9f-29d8-4409-97a1-6e50c5785334"
          },
          {
            "name": "YTD Revenue",
            "expression": "TOTALYTD(SUM([Revenue]),'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "48ab44f0-d8d9-476b-809e-28399cffd238",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Total COGS",
            "expression": "[Sum of Material Costs]+[Sum of Labor Costs Variable]+[Sum of Taxes]+[Sum of Rev for Exp Travel]+[Sum of Travel Expenses]+[Sum of Cost Third Party]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "5c0e55d7-09bf-4c38-95b6-ff49664cbc9f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD COGS",
            "expression": "TOTALYTD([Total COGS],'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "84e18f9a-024c-43e2-8fef-ff55abdd9b1b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD Gross Margin",
            "expression": "TOTALYTD([Gross Margin],'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e7d5bf3f-a438-42f7-b7c4-1ded594c0453",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Revenue SPLY",
            "expression": "CALCULATE([Total Revenue],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "be44f77a-8ca5-4301-9d56-bf59cf25b80a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Gross Margin SPLY",
            "expression": "CALCULATE([Gross Margin],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "848d236e-56d0-472c-b6b0-2a4b1b737cdf",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "GM% SPLY",
            "expression": "[Gross Margin SPLY]/[Revenue SPLY]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "51517f3c-12b2-4220-9f8a-0295db5c743b"
          },
          {
            "name": "YTD GM%",
            "expression": "[YTD Gross Margin]/[YTD Revenue]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "704b60e6-5c15-44ff-a71a-950bc3ba56de"
          },
          {
            "name": "YTD Revenue SPLY",
            "expression": "CALCULATE([YTD Revenue],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "f351366f-2dee-46d3-9589-01919607613c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "COGS SPLY",
            "expression": "CALCULATE([Total COGS],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "bf6d157d-7c9a-43f6-ab84-a1567d6ced41",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD COGS SPLY",
            "expression": "CALCULATE([YTD COGS],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "60e7d648-1ea6-4cdd-a554-2e898bd1a9fe",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD GM% SPLY",
            "expression": "[YTD GM SPLY]/[YTD Revenue SPLY]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b71ca39c-0132-4d1e-bf8f-83782889cf3f"
          },
          {
            "name": "YTD GM SPLY",
            "expression": "CALCULATE([YTD Gross Margin],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "52d8f3f6-2a8e-4993-ac7c-7f3b6e8a539a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY Rev Var",
            "expression": "[Total Revenue]-[Revenue SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "f7915a2f-4a3e-46fe-9664-956257abbad4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY GM Var",
            "expression": "[Gross Margin]-[Gross Margin SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d2fb8ca1-1b44-40d9-b131-cdbddee3114d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY Rev Growth",
            "expression": "IF([Revenue SPLY],[YoY Rev Var]/[Revenue SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "9820ccac-25dd-4e63-884a-495038ccf9f6"
          },
          {
            "name": "YoY GM Growth",
            "expression": "IF([Gross Margin SPLY],[YoY GM Var]/[Gross Margin SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "368a70fe-c3a6-4590-bfcf-950aa4268332"
          },
          {
            "name": "YoY YTD Rev Var",
            "expression": "[YTD Revenue]-[YTD Revenue SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "857475ca-2e25-4879-9581-0fe0b10a75f0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY COGS Var",
            "expression": "[Total COGS]-[COGS SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "49d27c16-3596-44d2-bbaa-9db403c68350",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY YTD COGS Var",
            "expression": "[YTD COGS]-[YTD COGS SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "428108ad-de9b-4346-9f90-d596be8de103",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY YTD GM% Var",
            "expression": "[YTD GM%]-[YTD GM% SPLY]",
            "formatString": "#,0",
            "lineageTag": "2e50b7c7-649a-492e-8203-b4bf24fc6768"
          },
          {
            "name": "YoY YTD GM Var",
            "expression": "[YTD Gross Margin]-[YTD GM SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "71be9f35-cf1c-424e-a9e2-99b0c958451f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY GM %Var",
            "expression": "[GM%]-[GM% SPLY]",
            "lineageTag": "0e54ed80-2605-4fb9-930c-64e2db50dbe8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "YoY YTD Rev Growth",
            "expression": "IF([YTD Revenue SPLY],[YoY YTD Rev Var]/[YTD Revenue SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7f18be36-d697-4b74-bcf8-be506d8abfac"
          },
          {
            "name": "YoY COGS Growth",
            "expression": "IF([COGS SPLY],[YoY COGS Var]/[COGS SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b29f64c9-75f4-465b-baaa-16f39e8eb75a"
          },
          {
            "name": "YoY YTD COGS Growth",
            "expression": "IF([YTD COGS SPLY],[YoY YTD COGS Var]/[YTD COGS SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "3fb39383-498c-4d16-8630-bc3ba78fd819"
          },
          {
            "name": "YoY YTD GM Growth",
            "expression": "IF([YTD GM SPLY],[YoY YTD GM Var]/[YTD GM SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "78466ed7-c711-4f3a-9c5b-69fd82636ac1"
          },
          {
            "name": "# of Customers",
            "expression": "DISTINCTCOUNT([Customer Key])",
            "lineageTag": "8429723a-ac81-4e32-a346-cfa0e77af549",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "# of Products",
            "expression": "DISTINCTCOUNT([Product Key])",
            "lineageTag": "fdb2f331-429f-4798-b1ee-0d1a8c7f56aa"
          },
          {
            "name": "Revenue Budget",
            "expression": "CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]=\"Budget\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "421d2aba-bb21-4779-93e6-1609176fd1ce",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Revenue Var to Budget",
            "expression": "[RevenueTY]-[Revenue Budget]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "47b6967a-a2b0-4da3-814b-e15f8ff883ae",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Revenue Var % to Budget",
            "expression": "DIVIDE([Revenue Var to Budget], [RevenueTY])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1e2732bb-90cb-4f98-b19e-9f3cb3483bf0"
          },
          {
            "name": "RevenueTY",
            "expression": "CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]=\"Actual\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "28c4b6cc-ec94-4667-8f02-d65839be7e44",
            "kpi": {
              "targetExpression": "'Fact'[Revenue Budget]",
              "targetFormatString": "\\$#,0;(\\$#,0);\\$#,0",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='Fact'[RevenueTY]/'Fact'[_RevenueTY Goal] return",
                "if(ISBLANK(x),BLANK(),",
                "        If(x<0.95,-1,",
                "\t    If(x<1,0,1)",
                "    )",
                ")",
                ""
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "Measure"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Percentage"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "95"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "100"
                }
              ]
            },
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Revenue",
            "expression": "SUM('Fact'[Revenue])",
            "lineageTag": "141cf333-44ef-4d76-bedc-715e9da67d27",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ]
      },
      {
        "name": "BU",
        "lineageTag": "201c6985-21d9-4962-b26c-d18a567a2020",
        "columns": [
          {
            "name": "BU Key",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BU Key",
            "lineageTag": "09f5e55b-0813-4dcb-8b2c-c1bdae6ed8eb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "BU",
            "dataType": "string",
            "sourceColumn": "BU",
            "lineageTag": "f6692aed-eee8-48dc-8332-c9f6a06af987",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Division",
            "dataType": "string",
            "sourceColumn": "Division",
            "lineageTag": "66ee6044-a7c8-406e-9fa7-9c4602ada68b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Executive_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Executive_id",
            "lineageTag": "4a7121e8-0fd1-4974-a73c-c68f46087d34",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "BU",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT #(lf)       #(lf)      [Profit Center Key] [BU Key],#(lf)   BU,#(lf)   Division, Executive_id#(lf)  FROM [MDS].[mdm].[profitcenter]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"BU Key\", \"BU Key\"}, {\"BU\", \"BU\"}, {\"Division\", \"Division\"}, {\"Executive_id\", \"Executive_id\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"BU Key\", type number}, {\"BU\", type text}, {\"Division\", type text}, {\"Executive_id\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "BUHierarchy",
            "lineageTag": "954d2d15-83b8-4239-be90-4279c698e1f7",
            "levels": [
              {
                "name": "Division",
                "ordinal": 0,
                "column": "Division",
                "lineageTag": "80b6b4b6-a11c-4a84-9c77-4587fd65ed70"
              },
              {
                "name": "BU",
                "ordinal": 1,
                "column": "BU",
                "lineageTag": "f53e8f1c-74fb-4a82-aba7-11df22fec95b"
              }
            ]
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "6d9bc81b-2fd3-4bd9-87fc-e465a3a2ed23",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "YearPeriod",
            "dataType": "string",
            "sourceColumn": "YearPeriod",
            "lineageTag": "7a10a869-a895-483b-b7be-2c4cc0649052",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "lineageTag": "eb09a792-282b-4521-aa28-fef21bc8fce5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Period",
            "dataType": "string",
            "sourceColumn": "Period",
            "lineageTag": "dc8ad5e4-e674-49a5-857b-8ef200a364d8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "General Date",
            "lineageTag": "fe6563b8-23e4-49aa-a9c0-0bd43c423015",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "db9c55a6-9978-4ac0-88b4-4f07ed8945a3",
                "defaultHierarchy": {
                  "table": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "sortByColumn": "Period",
            "lineageTag": "7ae7d154-b88f-4f1f-b5d0-45ad4177c91c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "QtrID",
            "dataType": "string",
            "sourceColumn": "QtrID",
            "lineageTag": "90464251-3a73-4e5a-9eb8-b50661cbfae1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Qtr",
            "dataType": "string",
            "sourceColumn": "Qtr",
            "lineageTag": "4e117d16-8b28-45a9-951a-dd2ec64b6d0b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT#(lf)       concat([Year], [period]) YearPeriod#(lf)#(tab)  ,[Year]#(lf)      ,[Period]#(lf)      ,[Date]#(lf)      ,[Month]#(lf)      ,[QtrID]#(lf)      ,[Qtr]#(lf)  FROM [MDS].[mdm].[fiscalperiod]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"YearPeriod\", \"YearPeriod\"}, {\"Year\", \"Year\"}, {\"Period\", \"Period\"}, {\"Date\", \"Date\"}, {\"Month\", \"Month\"}, {\"QtrID\", \"QtrID\"}, {\"Qtr\", \"Qtr\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"YearPeriod\", type text}, {\"Year\", Int64.Type}, {\"Period\", type text}, {\"Date\", type datetime}, {\"Month\", type text}, {\"QtrID\", type text}, {\"Qtr\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "YQM",
            "lineageTag": "07538d95-7350-4bb0-a8af-2930c74ab6fe",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "97639ffb-554f-4630-a2c8-16fdde0bd10e"
              },
              {
                "name": "Qtr",
                "ordinal": 1,
                "column": "Qtr",
                "lineageTag": "af4056a1-7795-452b-a2aa-c8e628afd90e"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "d07872e0-648a-4ce3-bd62-a5d2fa4421ed"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LegacyCustomDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Scenario",
        "lineageTag": "ade53bbd-ade0-4042-9d0b-0313c05347af",
        "columns": [
          {
            "name": "Scenario Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Scenario Key",
            "lineageTag": "b44e8a10-4d50-4bf5-80e4-682762d3631e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Scenario",
            "dataType": "string",
            "sourceColumn": "Scenario",
            "lineageTag": "6243b4fc-d3ef-4f94-8e16-29c4fb9c0520",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Scenario",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUXJMLilNzFGK1YlWMgJynUpT0lNLlGJjAQ==\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Column1\", \"Scenario Key\"}, {\"Column2\", \"Scenario\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Scenario Key\", Int64.Type}, {\"Scenario\", type text}})",
                " in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Product",
        "lineageTag": "11453577-e5ed-42eb-8d2c-55e3f16eb73f",
        "columns": [
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "lineageTag": "5f9190c1-7275-45e5-a100-decbc0cba2c0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product",
            "lineageTag": "c0613e88-25a4-404c-8535-e55b5bf2e3e1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMjRQ0lEKzi9LVIrViVYyAvECijJzS4vBfGMQ3yW/KD8dIm8C4rvnJKZkQhVYgAR8PXXNjSBcI5B8aV5eapFSbCwA\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Column1\", \"Product Key\"}, {\"Column2\", \"Product\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Product Key\", Int64.Type}, {\"Product\", type text}})",
                " in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Customer",
        "lineageTag": "599fd949-b71c-404b-8b7f-beb18f60b939",
        "columns": [
          {
            "name": "Customer",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Customer",
            "lineageTag": "09efa6c0-b4a8-4fd6-a129-95c581da603f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Country/Region",
            "dataType": "string",
            "sourceColumn": "Country/Region",
            "lineageTag": "255727b1-8569-4c8e-87ef-76b15c59ea40",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "715a6d02-0aa5-4512-9a13-b081f1ed0d3c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "194edd48-a723-44a5-a93b-894696445d35",
            "dataCategory": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Postal Code",
            "dataType": "double",
            "sourceColumn": "Postal Code",
            "lineageTag": "01c66d15-20b4-4329-91ea-790af3acb872",
            "dataCategory": "PostalCode",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "94dc528c-e1ce-4694-b08e-c941fc48f8e5",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Industry ID",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Industry ID",
            "lineageTag": "11b1ec53-36a4-467a-8411-be23efba2cd7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\mad\\Dropbox\\Work\\Obvience\\IP\\Customer and Product Profitability\\Data\\dimCustomer.xlsx\"), null, true),",
                "    Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Promoted Headers\", {{\"Customer\", \"Customer\"}, {\"Country\", \"Country/Region\"}, {\"Name\", \"Name\"}, {\"City\", \"City\"}, {\"Postal Code\", \"Postal Code\"}, {\"State\", \"State\"}, {\"Industry ID\", \"Industry ID\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Customer\", type number}, {\"Country/Region\", type text}, {\"Name\", type text}, {\"City\", type text}, {\"Postal Code\", type number}, {\"State\", type text}, {\"Industry ID\", type number}})",
                " in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "CustomerHierarchy",
            "lineageTag": "2b719065-df25-4a56-9b05-6646d2be8587",
            "levels": [
              {
                "name": "Country",
                "ordinal": 0,
                "column": "Country/Region",
                "lineageTag": "a737f704-ddd5-4b04-9d24-7ac221dcc27d"
              },
              {
                "name": "State",
                "ordinal": 1,
                "column": "State",
                "lineageTag": "fa88dcf4-ffa5-4c67-9025-990273f20b9c"
              },
              {
                "name": "City",
                "ordinal": 2,
                "column": "City",
                "lineageTag": "c74bdc42-b819-42f6-8fa4-c9feaea187fa"
              },
              {
                "name": "Postal Code",
                "ordinal": 3,
                "column": "Postal Code",
                "lineageTag": "2bd99c9e-b1df-41a1-a8f5-bab2a2605b9c"
              },
              {
                "name": "Customer",
                "ordinal": 4,
                "column": "Customer",
                "lineageTag": "d76ad330-fc32-441f-9949-cd8d4a13131c"
              }
            ]
          }
        ]
      },
      {
        "name": "Industry",
        "lineageTag": "24488d25-69e5-4b03-bded-55143997c94e",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "ID",
            "keepUniqueRows": true,
            "lineageTag": "a9ee22b5-9c75-4747-9f98-175f2985af51",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Industry",
            "dataType": "string",
            "sourceColumn": "Industry",
            "keepUniqueRows": true,
            "lineageTag": "f373dc40-3e4b-4c14-b732-0af4fa4691ef",
            "isDefaultLabel": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Image",
            "dataType": "binary",
            "sourceColumn": "Image",
            "lineageTag": "b7b38e40-0524-45de-8719-c746266602d5",
            "dataCategory": "Image",
            "isDefaultImage": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Industry",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT [dbo].[Industry].*   FROM [dbo].[Industry]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ID\", \"ID\"}, {\"Industry\", \"Industry\"}, {\"Image\", \"Image\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ID\", Int64.Type}, {\"Industry\", type text}, {\"Image\", type binary}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Executive",
        "lineageTag": "cb48c0ce-3942-4720-82db-452ea06d4f2f",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "ID",
            "keepUniqueRows": true,
            "lineageTag": "39351096-a049-4950-969b-5af86033bd3d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "1b91920a-bd73-4db4-9982-7e430f66d4cd",
            "isDefaultLabel": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Img",
            "dataType": "binary",
            "sourceColumn": "Img",
            "lineageTag": "e2f23e26-7d74-4791-82a9-45bfa52398e2",
            "dataCategory": "Image",
            "isDefaultImage": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Executive",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT [dbo].[Executive].*   FROM [dbo].[Executive]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ID\", \"ID\"}, {\"Name\", \"Name\"}, {\"Img\", \"Img\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ID\", Int64.Type}, {\"Name\", type text}, {\"Img\", type binary}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "State",
        "lineageTag": "6b27d9a8-c334-47f8-8bd8-90470820e08a",
        "columns": [
          {
            "name": "StateCode",
            "dataType": "string",
            "sourceColumn": "StateCode",
            "lineageTag": "e4cd5b1e-68fb-4319-b733-7095a5890aa7",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "0e538d04-07a0-4ad0-a5ff-de49bcb3cde8",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "a8750d76-5200-444e-919b-0b32eaaa10af",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "State",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"select StateShort StateCode, StateName State, Region from MDS.mdm.state\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"StateCode\", \"StateCode\"}, {\"State\", \"State\"}, {\"Region\", \"Region\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"StateCode\", type text}, {\"State\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_fe310476-3bb5-422b-85ff-9fd23f2cad67",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "0283330d-48eb-48f5-b937-d604f73a544f",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "b7afe999-97d6-42a3-8ca3-6eda6f26019a",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "1e166f72-7592-409d-ba2f-ce99e4fdf8d1",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "9b2b30d7-0d24-4c5e-b266-85684ee09299",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "2fdb269e-d5a4-4273-847b-638d6aad3049",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "b3d0475f-7466-4019-b6de-4fee1b0dab1e",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "bb9c4bfa-a05e-4c34-9a58-779b3cbe9063",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "7ec48c91-1891-4f6a-b7c6-2105fa87519b",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_fe310476-3bb5-422b-85ff-9fd23f2cad67-d67cdec0-80dc-4d14-91dc-f2af07fffba5",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "67e86470-e2f9-40b1-9ddf-02628f6b7a81",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "4e0334cd-62b2-4148-884e-84c324b0d2f8"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "006f5b25-fa0d-4118-87b3-5383dfaa1214"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "7fb3dcf4-2b48-4ba5-8a6d-14c10f4efaaa"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "0ef84df0-766a-4efa-b90c-32aa79f31e39"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "3afc2cf2-0f0a-42e1-9437-0eb1e4268496",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "bab464c1-f753-4d0d-8ebb-cd07ff8bf810",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "95cfc788-6fc3-49fe-a018-28abe583247d",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "717236bc-007e-41ff-b1c2-67a6934de88e",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "58df78d8-392d-425c-bc9a-ff637a8e7e0e",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "d20948cd-33a4-4811-b3be-f841a383bef7",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "4c59a548-fab5-44e8-bac5-3c3c2338ed34",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "b7954e95-6e3f-4e91-a8cc-87b027014549",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4-a8d78949-1742-4a86-af0b-cf59b84d8989",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Date'[Date])), 1, 1), Date(Year(MAX('Date'[Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "edf955cc-caba-4805-8017-38828dbaf929",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "26371180-d1c9-4a02-9d2e-0073c52fb80f"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "d215255b-813e-47ad-91e1-30bb7f754dfc"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "79667b37-7989-4de9-9f7b-96ec3d00cb81"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "03d7582a-9786-4f05-ac8b-ca42021e36e9"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "e8085e9d-6dc8-4c8e-a37d-a25c76158541",
        "fromTable": "Fact",
        "fromColumn": "BU Key",
        "toTable": "BU",
        "toColumn": "BU Key"
      },
      {
        "name": "e2d69975-1445-43f8-9008-c580d8b85e9d",
        "fromTable": "Fact",
        "fromColumn": "YearPeriod",
        "toTable": "Date",
        "toColumn": "YearPeriod"
      },
      {
        "name": "ae136884-d40d-4899-942c-0668a79c7420",
        "fromTable": "Fact",
        "fromColumn": "Scenario Key",
        "toTable": "Scenario",
        "toColumn": "Scenario Key"
      },
      {
        "name": "996dfaa0-cf16-4f01-9fee-9f472b727b09",
        "fromTable": "Fact",
        "fromColumn": "Product Key",
        "toTable": "Product",
        "toColumn": "Product Key"
      },
      {
        "name": "ec7a5ef0-70cf-4abe-8ac4-364a5e22f7c7",
        "fromTable": "Fact",
        "fromColumn": "Customer Key",
        "toTable": "Customer",
        "toColumn": "Customer"
      },
      {
        "name": "6d6ab90a-1617-476a-9783-aecb116ac11d",
        "fromTable": "BU",
        "fromColumn": "Executive_id",
        "toTable": "Executive",
        "toColumn": "ID"
      },
      {
        "name": "9249475f-a768-45d9-845e-83b653ccc793",
        "fromTable": "Customer",
        "fromColumn": "Industry ID",
        "toTable": "Industry",
        "toColumn": "ID"
      },
      {
        "name": "f433c520-c9a7-4ee0-a489-f737798ca886",
        "fromTable": "Customer",
        "fromColumn": "State",
        "toTable": "State",
        "toColumn": "StateCode"
      },
      {
        "name": "db9c55a6-9978-4ac0-88b4-4f07ed8945a3",
        "fromTable": "Date",
        "fromColumn": "Date",
        "toTable": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US",
            "DynamicImprovement": "HighConfidence"
          },
          "contentType": "json"
        }
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.105.664.0 (22.05)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Fact\",\"BU\",\"Date\",\"Scenario\",\"Product\",\"Customer\",\"Industry\",\"Executive\",\"State\"]"
      }
    ]
  }
}