{
  "name": "CustomerProfitabilitySamplePBIX_v1",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Fact",
        "isHidden": true,
        "lineageTag": "a1d326b4-b033-407c-8c12-6b39585f6c4c",
        "columns": [
          {
            "name": "Customer Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "lineageTag": "2bde6de0-87f4-4a68-b36b-ee2d8c2d7455",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "lineageTag": "2e077fe6-ca4a-473e-8286-ddeb6a5b7133",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "BU Key",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BU Key",
            "lineageTag": "7a44969d-bcc2-480d-822b-0538d5f5c8b2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Scenario Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Scenario Key",
            "lineageTag": "4ed5eeeb-6531-4070-a658-c40bc54d3c31",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Revenue",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Revenue",
            "lineageTag": "580cca2a-6c66-4d0a-820e-73f61e6b27e6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Material Costs",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Material Costs",
            "lineageTag": "b804f698-f63c-4613-b6d4-78636c234cca",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Labor Costs Variable",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Labor Costs Variable",
            "lineageTag": "1171bca1-4c4a-434d-bf2e-fbd3f171ba5c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Taxes",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Taxes",
            "lineageTag": "5c62e052-05cb-4211-bb73-64746f8c17ca",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Rev for Exp Travel",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rev for Exp Travel",
            "lineageTag": "b1233391-cd3e-4d06-a716-5db935b6215c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Travel Expenses",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Travel Expenses",
            "lineageTag": "e7bf9605-1de6-4f10-9266-5dd0395a213c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Cost Third Party",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Cost Third Party",
            "lineageTag": "f5812191-996d-4898-8e2d-f251cdd269bd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Subscription Revenue",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Subscription Revenue",
            "lineageTag": "e358e5be-14b1-49cb-b43c-f4f88182fd6d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "YearPeriod",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "YearPeriod",
            "lineageTag": "d044a69c-7fda-46a3-938d-ebd34d22970c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 YearPeriod#(lf)      ,[KNDNR] [Customer Key]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,1 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.20 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f, mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 210 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'#(lf)union all #(lf)SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 PeriodYear#(lf)      ,[KNDNR] [Customer]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,2 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.4 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f tablesample (85 percent),  mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 300 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Customer Key\", \"Customer Key\"}, {\"Product Key\", \"Product Key\"}, {\"BU Key\", \"BU Key\"}, {\"Scenario Key\", \"Scenario Key\"}, {\"Revenue\", \"Revenue\"}, {\"Material Costs\", \"Material Costs\"}, {\"Labor Costs Variable\", \"Labor Costs Variable\"}, {\"Taxes\", \"Taxes\"}, {\"Rev for Exp Travel\", \"Rev for Exp Travel\"}, {\"Travel Expenses\", \"Travel Expenses\"}, {\"Cost Third Party\", \"Cost Third Party\"}, {\"Subscription Revenue\", \"Subscription Revenue\"}, {\"YearPeriod\", \"YearPeriod\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Customer Key\", Int64.Type}, {\"Product Key\", type text}, {\"BU Key\", type number}, {\"Scenario Key\", Int64.Type}, {\"Revenue\", type number}, {\"Material Costs\", type number}, {\"Labor Costs Variable\", type number}, {\"Taxes\", type number}, {\"Rev for Exp Travel\", type number}, {\"Travel Expenses\", type number}, {\"Cost Third Party\", type number}, {\"Subscription Revenue\", type number}, {\"YearPeriod\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Revenue",
            "expression": "SUM([Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e6758cbd-8ac6-4aab-8f32-8740561a4233",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Material Costs",
            "expression": "SUM([Material Costs])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b24a9bcc-24ef-4ac3-b805-667526f495e3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Labor Costs Variable",
            "expression": "SUM([Labor Costs Variable])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a3c5b981-4d5f-4e04-8064-e5023f502fca",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Taxes",
            "expression": "SUM([Taxes])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "3ef82475-40b1-40b2-86e4-fff91550e4b1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Rev for Exp Travel",
            "expression": "SUM([Rev for Exp Travel])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8b51be86-8736-4997-89bb-a2f655fbd80c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Travel Expenses",
            "expression": "SUM([Travel Expenses])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "dd668f4d-0eef-4034-a1d7-dd2be38f9e9e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Cost Third Party",
            "expression": "SUM([Cost Third Party])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8fc056fc-acde-4ea0-b3e8-09f08a214cba",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Subscription Revenue",
            "expression": "SUM([Subscription Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b9b51f8d-5593-4b1a-95b6-a3427cf23c4e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Gross Margin",
            "expression": "[Total Revenue]-[Total COGS]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7e725e99-19ef-4d53-9e66-636fcf175cc1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "GM%",
            "expression": "DIVIDE([Gross Margin],[Total Revenue])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7d1c8b8e-8610-4ac0-8a77-8bd927d19fbc"
          },
          {
            "name": "YTD Revenue",
            "expression": "TOTALYTD(SUM([Revenue]),'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c37f7ae0-aefd-4511-acb5-da0a1955ae58",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Total COGS",
            "expression": "[Sum of Material Costs]+[Sum of Labor Costs Variable]+[Sum of Taxes]+[Sum of Rev for Exp Travel]+[Sum of Travel Expenses]+[Sum of Cost Third Party]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "5478d285-c170-4c20-8c37-59e2184eff8f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD COGS",
            "expression": "TOTALYTD([Total COGS],'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b59cbcdb-3263-49bc-8811-f94a6cd64da4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD Gross Margin",
            "expression": "TOTALYTD([Gross Margin],'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "be05ea21-970b-4d33-8f20-21fcff3f9278",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Revenue SPLY",
            "expression": "CALCULATE([Total Revenue],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "462a28db-47d5-4477-9a43-fc210ab3a51e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Gross Margin SPLY",
            "expression": "CALCULATE([Gross Margin],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1e36f764-989f-4d9a-a318-c8ef83e5c326",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "GM% SPLY",
            "expression": "[Gross Margin SPLY]/[Revenue SPLY]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "661aa398-5912-412c-be27-0b5dea4d517f"
          },
          {
            "name": "YTD GM%",
            "expression": "[YTD Gross Margin]/[YTD Revenue]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b21f9de8-4633-4f2c-b6b1-f89287af48a1"
          },
          {
            "name": "YTD Revenue SPLY",
            "expression": "CALCULATE([YTD Revenue],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e9dce3ea-768b-4f5d-baba-bbcb3d946314",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "COGS SPLY",
            "expression": "CALCULATE([Total COGS],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d3aac876-c323-4c78-81da-3d76ef927bc9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD COGS SPLY",
            "expression": "CALCULATE([YTD COGS],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "0824ea7f-385a-4c37-9ea5-8930d08a021c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YTD GM% SPLY",
            "expression": "[YTD GM SPLY]/[YTD Revenue SPLY]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "77de195a-0f64-41d6-85d4-58b5ee5573d2"
          },
          {
            "name": "YTD GM SPLY",
            "expression": "CALCULATE([YTD Gross Margin],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "689dffaf-7167-4796-b457-96d67934a6df",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY Rev Var",
            "expression": "[Total Revenue]-[Revenue SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "612f11a5-1a9d-4165-a1e5-0f3a347d6b0d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY GM Var",
            "expression": "[Gross Margin]-[Gross Margin SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "3756b667-e7dc-4511-b74d-291bec3fa41f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY Rev Growth",
            "expression": "IF([Revenue SPLY],[YoY Rev Var]/[Revenue SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "98f3b1c8-2998-4128-b222-07d4c5c0442c"
          },
          {
            "name": "YoY GM Growth",
            "expression": "IF([Gross Margin SPLY],[YoY GM Var]/[Gross Margin SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "abe091bd-db9e-4d79-a5be-db11d069ea8a"
          },
          {
            "name": "YoY YTD Rev Var",
            "expression": "[YTD Revenue]-[YTD Revenue SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "793c3449-02b7-4185-9cde-2be0e0878867",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY COGS Var",
            "expression": "[Total COGS]-[COGS SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "135ce0b1-fba5-4d01-bd3d-0a63b48d292f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY YTD COGS Var",
            "expression": "[YTD COGS]-[YTD COGS SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d597ab7d-baee-40ff-a374-97d6e04a7822",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY YTD GM% Var",
            "expression": "[YTD GM%]-[YTD GM% SPLY]",
            "formatString": "#,0",
            "lineageTag": "a50fd722-5de3-4c9e-93f2-67d7b510fe7a"
          },
          {
            "name": "YoY YTD GM Var",
            "expression": "[YTD Gross Margin]-[YTD GM SPLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d7bf331e-a253-4a57-a103-8f0e0b930cfe",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "YoY GM %Var",
            "expression": "[GM%]-[GM% SPLY]",
            "lineageTag": "ad7c7344-606c-40b9-a572-671d66e0735a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "YoY YTD Rev Growth",
            "expression": "IF([YTD Revenue SPLY],[YoY YTD Rev Var]/[YTD Revenue SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0329e7b5-5a46-478c-aa95-71888d3a4995"
          },
          {
            "name": "YoY COGS Growth",
            "expression": "IF([COGS SPLY],[YoY COGS Var]/[COGS SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dc1ad241-0945-4711-a81f-d4717abce527"
          },
          {
            "name": "YoY YTD COGS Growth",
            "expression": "IF([YTD COGS SPLY],[YoY YTD COGS Var]/[YTD COGS SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "91428d9e-efc9-4384-bef8-4cc0665f59a8"
          },
          {
            "name": "YoY YTD GM Growth",
            "expression": "IF([YTD GM SPLY],[YoY YTD GM Var]/[YTD GM SPLY],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ed0cda4c-3086-4b2e-ab81-037bd4202693"
          },
          {
            "name": "# of Customers",
            "expression": "DISTINCTCOUNT([Customer Key])",
            "lineageTag": "e9bcc753-782b-45fa-afa7-31d2f11be991",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "# of Products",
            "expression": "DISTINCTCOUNT([Product Key])",
            "lineageTag": "4b1fa4d1-ed8e-42d9-8bae-56c033d573b2"
          },
          {
            "name": "Revenue Budget",
            "expression": "CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]=\"Budget\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7d76aa62-9f7c-4707-9b6b-671ab94beb94",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Revenue Var to Budget",
            "expression": "[RevenueTY]-[Revenue Budget]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "599679f0-dced-48c1-bcdc-0a0d4eef2fff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Revenue Var % to Budget",
            "expression": "DIVIDE([Revenue Var to Budget], [RevenueTY])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "92d202ea-b529-48dc-8719-9c359a40a6f9"
          },
          {
            "name": "RevenueTY",
            "expression": "CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]=\"Actual\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "cb8fa6d6-f57b-4c93-8142-b55301f77813",
            "kpi": {
              "targetExpression": "'Fact'[Revenue Budget]",
              "targetFormatString": "\\$#,0;(\\$#,0);\\$#,0",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='Fact'[RevenueTY]/'Fact'[_RevenueTY Goal] return",
                "if(ISBLANK(x),BLANK(),",
                "        If(x<0.95,-1,",
                "\t    If(x<1,0,1)",
                "    )",
                ")",
                ""
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "Measure"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Percentage"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "95"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "100"
                }
              ]
            },
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sum of Revenue",
            "expression": "SUM('Fact'[Revenue])",
            "lineageTag": "b0598e8e-ea5d-4866-a895-34d65b017503",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ]
      },
      {
        "name": "BU",
        "lineageTag": "03018dfd-e2d5-410d-a003-babd7be1dfae",
        "columns": [
          {
            "name": "BU Key",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BU Key",
            "lineageTag": "4665e056-adb3-464b-9114-2e2da5739bb4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "BU",
            "dataType": "string",
            "sourceColumn": "BU",
            "lineageTag": "513e029f-404b-4962-b276-bcfde5f14a85",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Division",
            "dataType": "string",
            "sourceColumn": "Division",
            "lineageTag": "741b28a8-c412-4874-bdfc-7182a6ff797c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Executive_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Executive_id",
            "lineageTag": "751e8897-c999-4eb1-8504-bcc1c9ae09c6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "BU",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT #(lf)       #(lf)      [Profit Center Key] [BU Key],#(lf)   BU,#(lf)   Division, Executive_id#(lf)  FROM [MDS].[mdm].[profitcenter]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"BU Key\", \"BU Key\"}, {\"BU\", \"BU\"}, {\"Division\", \"Division\"}, {\"Executive_id\", \"Executive_id\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"BU Key\", type number}, {\"BU\", type text}, {\"Division\", type text}, {\"Executive_id\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "BUHierarchy",
            "lineageTag": "b6885faa-4f91-4d4f-8e93-54f0b4af7d3e",
            "levels": [
              {
                "name": "Division",
                "ordinal": 0,
                "column": "Division",
                "lineageTag": "bd3d250b-27ad-49db-af38-40d50ad0ec92"
              },
              {
                "name": "BU",
                "ordinal": 1,
                "column": "BU",
                "lineageTag": "5aad450a-27e2-4834-9693-9ef6ceaa09b0"
              }
            ]
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "528f724c-4dd5-41d0-9708-a0f60f7c1152",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "YearPeriod",
            "dataType": "string",
            "sourceColumn": "YearPeriod",
            "lineageTag": "7da2a578-281b-4c98-a8a2-09f771ae0256",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "lineageTag": "cd224f34-b902-48b0-a16a-d77a3e4471f8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Period",
            "dataType": "string",
            "sourceColumn": "Period",
            "lineageTag": "7a200271-96bd-487d-8e8a-47dc5293b377",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "General Date",
            "lineageTag": "b21f2109-6f5a-4089-9e72-ba5227c3607e",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "db9c55a6-9978-4ac0-88b4-4f07ed8945a3",
                "defaultHierarchy": {
                  "table": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "sortByColumn": "Period",
            "lineageTag": "4182776e-6f21-42da-840b-e9e2f35ee87e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "QtrID",
            "dataType": "string",
            "sourceColumn": "QtrID",
            "lineageTag": "52d98ab5-8381-4f67-b8e5-907e5f7cea3f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Qtr",
            "dataType": "string",
            "sourceColumn": "Qtr",
            "lineageTag": "a9618178-e45c-4025-833b-b9b843a37f2e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT#(lf)       concat([Year], [period]) YearPeriod#(lf)#(tab)  ,[Year]#(lf)      ,[Period]#(lf)      ,[Date]#(lf)      ,[Month]#(lf)      ,[QtrID]#(lf)      ,[Qtr]#(lf)  FROM [MDS].[mdm].[fiscalperiod]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"YearPeriod\", \"YearPeriod\"}, {\"Year\", \"Year\"}, {\"Period\", \"Period\"}, {\"Date\", \"Date\"}, {\"Month\", \"Month\"}, {\"QtrID\", \"QtrID\"}, {\"Qtr\", \"Qtr\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"YearPeriod\", type text}, {\"Year\", Int64.Type}, {\"Period\", type text}, {\"Date\", type datetime}, {\"Month\", type text}, {\"QtrID\", type text}, {\"Qtr\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "YQM",
            "lineageTag": "41209e92-5e76-4b7b-a264-c86366fe1cc7",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "28e08325-3e59-4393-b6fe-aeca9649ecf0"
              },
              {
                "name": "Qtr",
                "ordinal": 1,
                "column": "Qtr",
                "lineageTag": "4bf13935-52e7-44c7-a19f-4e74665613d1"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "45c293d2-911e-4fab-b98f-23be398f9910"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LegacyCustomDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Scenario",
        "lineageTag": "f418813c-3c6b-4935-960b-b3632681b4b3",
        "columns": [
          {
            "name": "Scenario Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Scenario Key",
            "lineageTag": "f3a31f57-93c7-4aab-adee-bd4d702d6279",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Scenario",
            "dataType": "string",
            "sourceColumn": "Scenario",
            "lineageTag": "fb000e26-12ef-433a-96b4-c0800ca8f308",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Scenario",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUXJMLilNzFGK1YlWMgJynUpT0lNLlGJjAQ==\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Column1\", \"Scenario Key\"}, {\"Column2\", \"Scenario\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Scenario Key\", Int64.Type}, {\"Scenario\", type text}})",
                " in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Product",
        "lineageTag": "4a387430-ccfa-4439-afd1-771775eab22a",
        "columns": [
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "lineageTag": "7e5bebe3-5cd2-4710-aee0-63710cd7255d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product",
            "lineageTag": "aaac3548-eb74-43d2-a561-e1083c5dabbe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMjRQ0lEKzi9LVIrViVYyAvECijJzS4vBfGMQ3yW/KD8dIm8C4rvnJKZkQhVYgAR8PXXNjSBcI5B8aV5eapFSbCwA\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Column1\", \"Product Key\"}, {\"Column2\", \"Product\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Product Key\", Int64.Type}, {\"Product\", type text}})",
                " in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Customer",
        "lineageTag": "affe8518-2712-482c-a123-6cb84df8cda7",
        "columns": [
          {
            "name": "Customer",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Customer",
            "lineageTag": "7c3294b6-b06b-47c4-b7af-0df4ff36f70b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Country/Region",
            "dataType": "string",
            "sourceColumn": "Country/Region",
            "lineageTag": "f1a6a290-1d38-4905-8b4e-702291f7987a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "7dc2050f-7bf3-4ff0-87bd-ed22be193eb7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "aac3b473-cbc1-48b3-bbf9-3cbf06b9797f",
            "dataCategory": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Postal Code",
            "dataType": "double",
            "sourceColumn": "Postal Code",
            "lineageTag": "9d5f1e85-5f12-474a-8394-c939198fe6b0",
            "dataCategory": "PostalCode",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "519eee0b-6976-4a1d-b3fc-2bbbd2fdc3c3",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Industry ID",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Industry ID",
            "lineageTag": "96f6eb17-e94d-4d8a-9cdf-fbf5e23aa10b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\mad\\Dropbox\\Work\\Obvience\\IP\\Customer and Product Profitability\\Data\\dimCustomer.xlsx\"), null, true),",
                "    Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Promoted Headers\", {{\"Customer\", \"Customer\"}, {\"Country\", \"Country/Region\"}, {\"Name\", \"Name\"}, {\"City\", \"City\"}, {\"Postal Code\", \"Postal Code\"}, {\"State\", \"State\"}, {\"Industry ID\", \"Industry ID\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Customer\", type number}, {\"Country/Region\", type text}, {\"Name\", type text}, {\"City\", type text}, {\"Postal Code\", type number}, {\"State\", type text}, {\"Industry ID\", type number}})",
                " in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "CustomerHierarchy",
            "lineageTag": "a7b6b7f2-46e7-4b71-af1b-60a9976c5651",
            "levels": [
              {
                "name": "Country",
                "ordinal": 0,
                "column": "Country/Region",
                "lineageTag": "b9956b8c-b439-4f4a-aace-85384b05e49e"
              },
              {
                "name": "State",
                "ordinal": 1,
                "column": "State",
                "lineageTag": "445dd361-7efc-47ae-bc5a-9ad850fe741e"
              },
              {
                "name": "City",
                "ordinal": 2,
                "column": "City",
                "lineageTag": "5beff77e-1eef-4837-8706-b9c052d2fbd9"
              },
              {
                "name": "Postal Code",
                "ordinal": 3,
                "column": "Postal Code",
                "lineageTag": "df2c9a43-632b-42cf-af16-b28c558cef98"
              },
              {
                "name": "Customer",
                "ordinal": 4,
                "column": "Customer",
                "lineageTag": "d7919f7a-e256-4fb1-a09e-069a90376688"
              }
            ]
          }
        ]
      },
      {
        "name": "Industry",
        "lineageTag": "a1344922-ccf8-4d94-9d6c-632c65aa4401",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "ID",
            "keepUniqueRows": true,
            "lineageTag": "9c932103-d1e2-4c2d-917f-b3e285cd23e7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Industry",
            "dataType": "string",
            "sourceColumn": "Industry",
            "keepUniqueRows": true,
            "lineageTag": "4936fe6c-d2a6-4e5a-8c0a-fe383b173172",
            "isDefaultLabel": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Image",
            "dataType": "binary",
            "sourceColumn": "Image",
            "lineageTag": "a148ad16-6c2c-4a48-977b-3f9527e62ce1",
            "dataCategory": "Image",
            "isDefaultImage": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Industry",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT [dbo].[Industry].*   FROM [dbo].[Industry]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ID\", \"ID\"}, {\"Industry\", \"Industry\"}, {\"Image\", \"Image\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ID\", Int64.Type}, {\"Industry\", type text}, {\"Image\", type binary}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Executive",
        "lineageTag": "3d4a774a-da99-42d6-b673-ceeeed8e6293",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "ID",
            "keepUniqueRows": true,
            "lineageTag": "564f6689-1fb8-48ed-8266-021d9f048d50",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "11eba444-1770-467e-ad1a-f13bf2e2876f",
            "isDefaultLabel": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Img",
            "dataType": "binary",
            "sourceColumn": "Img",
            "lineageTag": "ef0a23b5-0f2e-4f7d-8a38-fa2e13bd1030",
            "dataCategory": "Image",
            "isDefaultImage": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Executive",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT [dbo].[Executive].*   FROM [dbo].[Executive]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ID\", \"ID\"}, {\"Name\", \"Name\"}, {\"Img\", \"Img\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ID\", Int64.Type}, {\"Name\", type text}, {\"Img\", type binary}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "State",
        "lineageTag": "58c80180-0ab3-4650-9f80-e267782945e3",
        "columns": [
          {
            "name": "StateCode",
            "dataType": "string",
            "sourceColumn": "StateCode",
            "lineageTag": "d6ec9133-0770-46d2-bb23-dbbcb15151df",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "fe125743-b58e-4c8b-a261-67d96de65f79",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "4952e913-c34a-4157-9748-ad212e332407",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "State",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"select StateShort StateCode, StateName State, Region from MDS.mdm.state\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"StateCode\", \"StateCode\"}, {\"State\", \"State\"}, {\"Region\", \"Region\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"StateCode\", type text}, {\"State\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_fe310476-3bb5-422b-85ff-9fd23f2cad67",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e5f6e613-3491-47c2-bfc1-1a8cf510b2d2",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "4f20b7ad-42db-40c4-8be7-d9bf86d5dea4",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "6dd17aa7-5137-4a81-a0c6-64ded7820e91",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "ada9c6e9-7803-4a07-9d69-67ae5d14baaf",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "d830618d-d838-4d8e-a979-196d9ad189f0",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "5e0a88a1-9ce1-4a21-9f6a-3b15848727f7",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "c8f3e20c-44fc-4252-9574-52ddb7e896ca",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "b1c99358-fae6-4521-a4df-6cba64eda36c",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_fe310476-3bb5-422b-85ff-9fd23f2cad67-d67cdec0-80dc-4d14-91dc-f2af07fffba5",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "bd1f3f06-23d8-420b-8318-095975e6570b",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "78b48936-0269-4fcb-8743-61f99880618f"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "495c2ed9-999d-4db2-99f1-6a20303a0d67"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "e3877272-bad1-44fa-8e5c-ed2a9ceb7ade"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "6f93931e-535a-4d74-8568-909ee9e399b8"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "07d2fc90-a44f-4568-8b6d-004a9091d0d4",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "d7c6692d-61a9-46b2-9ddd-44028528154b",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "fb707a23-9a75-4829-8b1c-235f3b8d1833",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "bb17a764-93d1-4f4f-8bff-261ffe2d63a5",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "8cc00a59-287b-4fb5-9839-560e37adfd56",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "50c8644a-7b4e-44a1-abc7-b1c19048f009",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "dd02fa3c-bb12-4792-b70b-74498861be13",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "e1ca25ff-bdfb-473d-a0eb-49586c236095",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4-a8d78949-1742-4a86-af0b-cf59b84d8989",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Date'[Date])), 1, 1), Date(Year(MAX('Date'[Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "7e623d94-3da3-44ac-9811-60914ba5fa2c",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "1dad7153-7e79-40d3-bbee-4b48cd1b5284"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "cb03a6ef-e5b3-45a7-98ab-bc1d70fc5dc8"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "6c2cd4d6-1128-46a1-b310-129b186f9ab9"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "087a772c-6b70-4c0a-bb2f-42102e357a45"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "e8085e9d-6dc8-4c8e-a37d-a25c76158541",
        "fromTable": "Fact",
        "fromColumn": "BU Key",
        "toTable": "BU",
        "toColumn": "BU Key"
      },
      {
        "name": "e2d69975-1445-43f8-9008-c580d8b85e9d",
        "fromTable": "Fact",
        "fromColumn": "YearPeriod",
        "toTable": "Date",
        "toColumn": "YearPeriod"
      },
      {
        "name": "ae136884-d40d-4899-942c-0668a79c7420",
        "fromTable": "Fact",
        "fromColumn": "Scenario Key",
        "toTable": "Scenario",
        "toColumn": "Scenario Key"
      },
      {
        "name": "996dfaa0-cf16-4f01-9fee-9f472b727b09",
        "fromTable": "Fact",
        "fromColumn": "Product Key",
        "toTable": "Product",
        "toColumn": "Product Key"
      },
      {
        "name": "ec7a5ef0-70cf-4abe-8ac4-364a5e22f7c7",
        "fromTable": "Fact",
        "fromColumn": "Customer Key",
        "toTable": "Customer",
        "toColumn": "Customer"
      },
      {
        "name": "6d6ab90a-1617-476a-9783-aecb116ac11d",
        "fromTable": "BU",
        "fromColumn": "Executive_id",
        "toTable": "Executive",
        "toColumn": "ID"
      },
      {
        "name": "9249475f-a768-45d9-845e-83b653ccc793",
        "fromTable": "Customer",
        "fromColumn": "Industry ID",
        "toTable": "Industry",
        "toColumn": "ID"
      },
      {
        "name": "f433c520-c9a7-4ee0-a489-f737798ca886",
        "fromTable": "Customer",
        "fromColumn": "State",
        "toTable": "State",
        "toColumn": "StateCode"
      },
      {
        "name": "db9c55a6-9978-4ac0-88b4-4f07ed8945a3",
        "fromTable": "Date",
        "fromColumn": "Date",
        "toTable": "LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US",
            "DynamicImprovement": "HighConfidence"
          },
          "contentType": "json"
        }
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.110.1161.0 (22.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Fact\",\"BU\",\"Date\",\"Scenario\",\"Product\",\"Customer\",\"Industry\",\"Executive\",\"State\"]"
      }
    ]
  }
}